# Generated by Django 4.2.6 on 2023-11-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='receipt',
        ),
        migrations.AddField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(default='Default Generic Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
    ]
