# Generated by Django 4.2.6 on 2023-11-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0003_alter_drug_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
