# Generated by Django 4.2.6 on 2023-12-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receipts', '0008_provision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.IntegerField(default=0)),
                ('cost_price', models.IntegerField(default=0)),
                ('former_quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.receipt')),
            ],
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='drug_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='provision',
            old_name='product_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='SupplierSupply',
        ),
        migrations.AddField(
            model_name='item',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.drug'),
        ),
        migrations.AddField(
            model_name='item',
            name='provision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receipts.provision'),
        ),
    ]
